version: "3.5"

services:
    django:
        build:
            dockerfile: etc/django.Dockerfile
            context: .
        command: bash -c "while true; do echo 'I am alive!'; sleep 3600; done"
        ports:
            - 8000:8000
            - 5555:5555
        environment:
            - C_FORCE_ROOT=true
        links:
            - postgres:postgres.local
            - redis:redis.local
        volumes:
            - .:/webapp
            
    postgres:
        image: postgres:12
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        volumes:
            - postgres-volume:/var/lib/postgresql/data
            
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - 6060:80
        links:
            - postgres:postgres.local
            
    redis:
        image: "redis:alpine"


volumes:
    postgres-volume:
    pgadmin:
